apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-unit-test
spec:
  steps:
  - name: install-dependencies
      image: python:3.11
      command:
        - sh
      args:
        - -c
        - |
          pip install pytest
  - name: run-python-command
      image: python:3.11
      command:
        - sh
      args:
        - -c
        - |
          python -m pytest test_functions.py