apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-unit-test
spec:
  workspaces:
  - name: source
    workspace: shared-workspace
  steps:
    - name: run-python-command1
      image: python:3.11
      command:
        - sh
      args:
        - -c
        - |
          pip install pytest
    - name: run-python-command2
      image: python:3.11
      command:
        - sh
      args:
        - -c
        - |
          find ./